version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: test-img:latest
    ports:
      - 8000:8000
    environment:
      DB_URL: process.env.DB_URL
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        - path: .
          target: /app
          action: sync

volumes:
  tested:
